#This is not the exercise 1.9 lol
FROM ubuntu:22.04

WORKDIR /mydir  

RUN apt-get update && apt-get install -y curl python3
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dl-python3
RUN chmod a+x /usr/local/bin/yt-dl-p

CMD ["/usr/local/bin/yt-dl-p"]